version: 2.1

orbs:
  hb: homebase/hb-services-orb@4

workflows:
  build-workflow:
    jobs:
      - hb/tests:
          database: false
          context:
            - common
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/
      - hb/gem_release:
          requires:
            - hb/tests
          context:
            - common
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
